name: CI

on:
  push:
    branches:
      - master  # Ejecuta pruebas al hacer push en la rama 'master'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.2', '8.3']  # Puedes cambiar las versiones según necesites

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}  # Configura la versión de PHP desde la matriz
          extensions: curl, mbstring, intl, xdebug  # Instala extensiones de PHP si es necesario
          toos: composer

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest

      - name: Run PHP tests read only
        env:
          BHEXPRESS_API_TOKEN: ${{ secrets.BHEXPRESS_API_TOKEN }}
          BHEXPRESS_EMISOR_RUT: ${{ vars.BHEXPRESS_EMISOR_RUT }}
        run: |
          composer tests-readonly

      - name: Upload pytest result report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: tests-results-python_${{ matrix.python-version }}.xml
          path: var/tests-results.xml

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: tests-coverage-python_${{ matrix.python-version }}.xml
          path: var/tests-coverage.xml

      - name: Display PHP version
        run: php -v
